@startuml
digraph G {
"Initial commit (763ab86)" [shape=box]
"commit1 (15bb8d5)" [shape=box]
  "Initial commit (763ab86)" -> "commit1 (15bb8d5)"
"create file test.txt (15bb8)" [shape=ellipse]
  "commit1 (15bb8d5)" -> "create file test.txt (15bb8)"
"commit2 (5324bbd)" [shape=box]
  "commit1 (15bb8d5)" -> "commit2 (5324bbd)"
"create file test2.txt (5324b)" [shape=ellipse]
  "commit2 (5324bbd)" -> "create file test2.txt (5324b)"
"commit3 (cf9886d)" [shape=box]
  "commit2 (5324bbd)" -> "commit3 (cf9886d)"
"create file qwe.txt (cf988)" [shape=ellipse]
  "commit3 (cf9886d)" -> "create file qwe.txt (cf988)"
"edit file test.txt (cf988)" [shape=ellipse]
  "commit3 (cf9886d)" -> "edit file test.txt (cf988)"
"commit4 (2299184)" [shape=box]
  "commit3 (cf9886d)" -> "commit4 (2299184)"
"edit file qwe.txt (22991)" [shape=ellipse]
  "commit4 (2299184)" -> "edit file qwe.txt (22991)"
"remove file test2.txt (22991)" [shape=ellipse]
  "commit4 (2299184)" -> "remove file test2.txt (22991)"
}
@enduml